
# start wsl and run the "tmux a" command
shell = "wsl tmux a"

#shell = "ubuntu" # same thing as wsl

[keyboard]
	bindings = [
		{ key = "Space", mods = "Control", chars = "\u0000" },
	]

[selection]
	save_to_clipboard = true

[window]
	startup_mode = "Maximized"
	#startup_mode = "Fullscreen"

	## setting decorations = "None" has several bugs:
	##
	## - mouse cursor doesn't show
	## - opacity doesn't work
	## - obs can't record alacritty
	##
	## fullscreen has similar bug(s)
	##
	#decorations = "None"

	decorations = "Full"

	#opacity = 0.7
	opacity = 1.0

[font]
	size = 19

[colors.normal]
	blue  = "#1166cc"
	green = "#11cc66"

[colors.primary]

	#background = "#262626"  # tokyonight-moon nvim background
	background = "#1f1f1f"   # halfway
	#background = "#181818"  # alacritty default

	foreground = "#f2f2f2"   # laptop screen isn't at full brightness anyway
	#foreground = "#d8d8d8"  # alacritty default

