
## start wsl and run the "tmux a" command
#shell = "wsl tmux a"

shell = "wsl"
#shell = "ubuntu" # same thing as wsl

[keyboard]
	bindings = [
		{ key = "Space", mods = "Control", chars = "\u0000" },
		{ key = "NumpadEnter", chars = "\u000d" },
	]

#mouse_bindings:
#	- { mouse: Middle, mods: Shift, action: PasteSelection }
#	- { mouse: Right,  mods: Shift, action: Paste }
#	- { mouse: Middle,  action: None }
#	- { mouse: Right,  action: None }
[mouse]
	bindings = [
		{ mouse = "Middle", mods = "Shift", action = "PasteSelection" },
		{ mouse = "Right" , mods = "Shift", action = "Paste" },
		{ mouse = "Middle", action = "None" },
		{ mouse = "Right" , action = "None" },
	]

[selection]
	save_to_clipboard = true

[window]
	startup_mode = "Maximized"
	#startup_mode = "Fullscreen"

	## setting decorations = "None" has several bugs:
	##
	## - mouse cursor doesn't show
	## - opacity doesn't work
	## - obs can't record alacritty
	##
	## fullscreen has similar bug(s)
	##
	#decorations = "None"

	decorations = "Full"

	# Opacity didn't seem to work before but after several Windows updates it
	# seems ok maybe?
	opacity = 0.85
	#opacity = 1.0

[font]
	size = 19

[colors.normal]
	blue  = "#1166cc"
	green = "#11cc66"

[colors.primary]

	#background = "#262626"  # tokyonight-moon nvim background
	#background = "#1f1f1f"   # halfway
	background = "#181818"  # alacritty default

	foreground = "#f2f2f2"   # laptop screen isn't at full brightness anyway
	#foreground = "#d8d8d8"  # alacritty default

[debug]
	# What I want to do is turn off the popups at the bottom of the window, but
	# this doesn't do it by itself.  Apparently you also have to start alacritty
	# as `alacritty -qq` for that (one q `-q` isn't enough)
	log_level = "Error"
	#log_level = "Warn"  # default
	#log_level = "Off"

